version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  canvas_db_dba_password:
    external: true


configs:
  canvas_cache:
    external: true
  canvas_database:
    external: true
  canvas_delayed_jobs:
    external: true
  canvas_dev_loc:
    external: true
  canvas_domain:
    external: true
  canvas_outgoing_mail:
    external: true
  canvas_redis:
    external: true
  canvas_security:
    external: true
  canvas_wait:
    external: true

services:
  canvas-db:
    image: 192.87.106.18:56001/postgres:0.1
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/postgresql/data
    secrets:
      - canvas_db_dba_password
    networks:
      - $STACK_NETWORK
    environment:
      POSTGRES_DB:       canvas
      POSTGRES_USER:     canvas
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/canvas_db_dba_password

  canvas-redis:
    image: redis:3.2.4
    command: redis-server --appendonly yes
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/redis:/data
    networks:
      - $STACK_NETWORK
  
  app: &app
    image: 192.87.106.18:56001/canvas:0.1
    command: bash -c "./wait-for-it.sh -t 40 canvas-db:5432 && /usr/src/entrypoint"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 200s      
    environment:
      - CANVAS_DOMAIN=$STACK_DOMAIN
      - DB_DRIVER=postgresql
      - DB_HOST=canvas-db
      - DB_PORT=5432
      - DB_USERNAME=canvas
      - DB_PASSWORD_FILE= /run/secrets/canvas_db_dba_password
      - DB_NAME=canvas
      - RAILS_ENV=production
      - REDIS_SERVER=redis://canvas-redis:6379
      - MAIL_SERVER=outgoing.mf.surf.nl
      - MAIL_PORT=25
      - MAIL_DOMAIN=surf.nl
      - MAIL_DEFAULT_SENDER_ADDRESS=no-reply@surf.nl
      - MAIL_DEFAULT_SENDER_NAME=Canvas Admin
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/brandable_css:/usr/src/app/public/dist/brandable_css
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp:/usr/src/app/tmp
    secrets:
      - canvas_db_dba_password
    configs:
      - source: canvas_cache
        target: /usr/src/app/config/cache.yml
      - source: canvas_database
        target: /usr/src/app/config/database.yml      
      - source: canvas_delayed_jobs
        target: /usr/src/app/config/delayed_jobs.yml
      - source: canvas_dev_loc
        target: /usr/src/app/config/development-local.rb
      - source: canvas_domain
        target: /usr/src/app/config/domain.yml
      - source: canvas_outgoing_mail
        target: /usr/src/app/config/outgoing_mail.yml
      - source: canvas_redis
        target: /usr/src/app/config/redis.yml     
      - source: canvas_security
        target: /usr/src/app/config/security.yml
      - source: canvas_wait
        target: /usr/src/app/wait-for-it.sh  
        mode: 0755
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80

  worker:
    <<: *app
    command: bundle exec script/delayed_job run
    ports:
      - $STACK_PORT2:80