version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  canvas_db_dba_password:
    external: true
  canvas_secret_api:
    external: true

services:
  canvas-db:
    image: 192.87.106.18:56001/postgres:0.1
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/postgresql/data
    secrets:
      - canvas_db_dba_password
    networks:
      - $STACK_NETWORK
    environment:
      POSTGRES_DB:       canvas
      POSTGRES_USER:     canvas
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/canvas_db_dba_password

  app: &app
    image: 192.87.106.18:56001/canvas:0.1
    command: bash -c "./config/wait-for-it.sh -t 40 canvas-db:5432 && ./config/startup.sh"
    hostname: $STACK_DOMAIN
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 200s      
    environment:
      - IDP_URL=$STACK_NETWORK_URL_IDP
      - IDP_FINGERPRINT=$STACK_NETWORK_IDP_FINGERPRINT
      - CANVAS_DOMAIN=$STACK_DOMAIN
      - CANVAS_SECRET_API_FILE= /run/secrets/canvas_secret_api
      - DB_DRIVER=postgresql
      - DB_HOST=canvas-db
      - DB_PORT=5432
      - DB_USERNAME=canvas
      - DB_PASSWORD_FILE= /run/secrets/canvas_db_dba_password
      - DB_NAME=canvas
      - RAILS_ENV=production
      - MAIL_SERVER=outgoing.mf.surf.net
      - MAIL_PORT=25
      - MAIL_DOMAIN=surf.nl
      - MAIL_DEFAULT_SENDER_ADDRESS=no-reply@surf.nl
      - MAIL_DEFAULT_SENDER_NAME=Canvas Admin
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/brandable_css:/usr/src/app/public/dist/brandable_css
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp:/usr/src/app/tmp
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/cache.yml:/usr/src/app/config/cache.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/create_login.sh:/usr/src/app/config/create_login.sh
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/database.yml:/usr/src/app/config/database.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/delayed_jobs.yml:/usr/src/app/config/delayed_jobs.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/development-local.rb:/usr/src/app/config/development-local.rb
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/domain.yml:/usr/src/app/config/domain.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/outgoing_mail.yml:/usr/src/app/config/outgoing_mail.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/security.yml:/usr/src/app/config/security.yml
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/startup.sh:/usr/src/app/config/startup.sh
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/testmail.sh:/usr/src/app/config/testmail.sh
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf/wait-for-it.sh:/usr/src/app/config/wait-for-it.sh
    secrets:
      - canvas_db_dba_password
      - canvas_secret_api
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80

  worker:
    <<: *app
    command: bundle exec script/delayed_job run
    ports:
      - $STACK_PORT2:80
