version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  canvas_db_dba_password:
    external: true
  canvas_secret_api:
    external: true

services:
  canvas-db:
    image: 192.87.106.18:56001/postgres:0.1
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/postgresql/data
    secrets:
      - canvas_db_dba_password
    networks:
      - $STACK_NETWORK
    environment:
      POSTGRES_DB:       canvas
      POSTGRES_USER:     canvas
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/canvas_db_dba_password

  app: 
    image: 192.87.106.18:56001/canvas:0.1
    command: bash -c "./config/wait-for-it.sh -t 40 canvas-db:5432 && ./config/startup.sh"
    deploy:
      replicas: 1
      restart_policy:
        condition: none    
    environment:
      - CANVAS_LMS_ADMIN_EMAIL=ronald.ham@surfnet.nl
      - CANVAS_LMS_ADMIN_PASSWORD=$STACK_PASSWORD
      - CANVAS_LMS_STATS_COLLECTION=opt_out
      - CANVAS_LMS_ACCOUNT_NAME=SURFnetDLO
      - CANVAS_DOMAIN=$STACK_DOMAIN
      - DB_DRIVER=postgresql
      - DB_HOST=canvas-db
      - DB_PORT=5432
      - DB_USERNAME=canvas
      - DB_PASSWORD_FILE= /run/secrets/canvas_db_dba_password
      - CANVAS_SECRET_API_FILE= /run/secrets/canvas_secret_api
      - DB_NAME=canvas
      - RAILS_ENV=production
      - REDIS_SERVER=redis://redis:6379
      - MAIL_SERVER=outgoing.mf.surf.nl
      - MAIL_PORT=25
      - MAIL_DOMAIN=surf.nl
      - MAIL_DEFAULT_SENDER_ADDRESS=no-reply@surf.nl
      - MAIL_DEFAULT_SENDER_NAME=Canvas Admin
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/brandable_css:/usr/src/app/public/dist/brandable_css
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp:/usr/src/app/tmp
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/configs:/usr/src/app/config
    secrets:
      - canvas_db_dba_password
      - canvas_secret_api
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80

