version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  canvas_db_dba_password:
    external: true

services:
  canvas-db:
    image: 192.87.106.18:56001/postgres:0.1
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/postgresql/data
    secrets:
      - canvas_db_dba_password
    networks:
      - $STACK_NETWORK
    environment:
      POSTGRES_DB:       canvas
      POSTGRES_USER:     canvas
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/canvas_db_dba_password

  canvas-redis:
    image: redis:3.2.4
    command: redis-server --appendonly yes
    sysctls:
      net.core.somaxconn: 511
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/redis:/data
    networks:
      - $STACK_NETWORK
  
  app: &app
    image: 192.87.106.18:56001/canvas:0.1
    command: bash -c "./config/wait-for-it.sh -t 40 canvas-db:5432 && /usr/src/entrypoint"
    hostname: $STACK_DOMAIN
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 200s      
    environment:
      - CANVAS_DOMAIN=$STACK_DOMAIN
      - DB_DRIVER=postgresql
      - DB_HOST=canvas-db
      - DB_PORT=5432
      - DB_USERNAME=canvas
      - DB_PASSWORD_FILE= /run/secrets/canvas_db_dba_password
      - DB_NAME=canvas
      - RAILS_ENV=production
      - REDIS_SERVER=redis://canvas-redis:6379
      - MAIL_SERVER=outgoing.mf.surf.net
      - MAIL_PORT=25
      - MAIL_DOMAIN=surf.nl
      - MAIL_DEFAULT_SENDER_ADDRESS=no-reply@surf.nl
      - MAIL_DEFAULT_SENDER_NAME=Canvas Admin
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/brandable_css:/usr/src/app/public/dist/brandable_css
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp:/usr/src/app/tmp
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/configs:/usr/src/app/config
    secrets:
      - canvas_db_dba_password
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80

  worker:
    <<: *app
    command: bundle exec script/delayed_job run
    ports:
      - $STACK_PORT2:80