production: &default
  # replace this with a random string of at least 20 characters
  encryption_key: tiovtgfxe47qpuzqcp4zjluj7l36fqkmi9hb73kh
  lti_iss: <%= ENV['CANVAS_DOMAIN'] %>

development:
  <<: *default
  encryption_key: tiovtgfxe47qpuzqcp4zjluj7l36fqkmi9hb73kh
  #previous_encryption_keys:
  #  - facdd3a131ddd8988b14f6e4e01039c93cfa0160

test:
  <<: *default
  encryption_key: tiovtgfxe47qpuzqcp4zjluj7l36fqkmi9hb73kh
